### ISSUE TITLE
CLI - Invalid or unexpected token (on the shebang)

### ISSUE THREAD

**Issue by MrChocolatine** [keithamus/sort-package-json#163]
I don't know if my issue is entirely due to your package but I must start posting it somewhere (and as it is the first package mentioned in my log...)

I am working on EmberJS projects and for approximatively 2 weeks I always get this error from the command-line:

![00](https://user-images.githubusercontent.com/47531779/76413191-e6faf880-638c-11ea-8d1c-a472b562e212.png)

<details>
  <summary>Content of the log file mentioned in the screenshot (click to toggle):</summary>
  
```
=================================================================================

ENV Summary:

  TIME: Wed Mar 11 2020 11:37:53 GMT+0000 (Greenwich Mean Time)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node@12/12.16.1/bin/node
  - /usr/local/bin/ember
  - help
  - generate
  EXEC_PATH: /usr/local/Cellar/node@12/12.16.1/bin/node
  TMPDIR: /var/folders/19/vqwg83651n772jt7n0914f6c0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/opt/node@12/bin
  - /Users/_my_user_/bin
  - /usr/local/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/X11/bin
  PLATFORM: darwin x64
  FREEMEM: 907194368
  TOTALMEM: 17179869184
  UPTIME: 1192041
  LOADAVG: 2.28857421875,2.46240234375,2.21533203125
  CPUS:
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.9.3
  - icu: 64.2
  - llhttp: 2.0.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.40.0
  - node: 12.16.1
  - openssl: 1.1.1d
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.34.0
  - v8: 7.8.279.23-node.31
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Invalid or unexpected token
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Invalid or unexpected token
  - name: SyntaxError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: /Users/_my_user_/Dev/_some_private_path/_playground/node_modules/sort-package-json/index.js:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1059:15)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/blueprints/addon/index.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Function.Blueprint.load (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/blueprint.js:1309:31)
    at /Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/blueprint.js:1346:33
    at Array.map (<anonymous>:null:null)
    at /Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/blueprint.js:1345:38
    at Array.map (<anonymous>:null:null)
    at Function.Blueprint.list (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/blueprint.js:1336:22)
    at Class.getAllBlueprints (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/generate.js:92:35)
    at Class.printDetailedHelp (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/generate.js:83:28)
    at Class._printHelpForCommand (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/help.js:114:15)
    at Class.<anonymous> (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/help.js:86:14)
    at Array.forEach (<anonymous>:null:null)
    at Class._printHelp (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/help.js:85:15)
    at Class.run (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/commands/help.js:27:12)
    at /Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/command.js:311:20
    at initializePromise (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1017:35)
    at Class.validateAndRun (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/models/command.js:263:12)
    at /Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/lib/cli/cli.js:183:28
    at tryCatcher (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at publish (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:484:9)
    at flush (/Users/_my_user_/Dev/_some_private_path/_playground/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)


=================================================================================
```
</details>

As you can see the `#!/usr/bin/env node` seems to be the problem, that I can temporarily fix by commenting the line.

I tried to reinstall my `node_modules`, my EmberJS dependencies, Node.js... Still have the problem.

I never ever had this issue in any of my projects for years... This is also weird as I still have other files that use the same shebang:
![01](https://user-images.githubusercontent.com/47531779/76414099-94224080-638e-11ea-89e6-e35cd13f22c6.png)

**Comment by keithamus** [comment]
@MrChocolatine that seems frustrating. I don't know what `ember` does with your `node_modules` folder but I think it's worth filing with them.

I'm not sure what we can really do within this package; the shebang line needs to be there so the CLI works, so we can't really change our code to fit Ember. I'll close this because I don't really see an actionable path forward.

**Comment by MrChocolatine** [comment]
I didn't mean to "fit Ember" but maybe the concatenation or whatever could possibly be faulty. I am still investigating what is wrong (and again, I am was not convinced your package was the guilty one).

**Comment by keithamus** [comment]
It's strange because the only file with the shebang is our `cli.js` - which is only referenced as a `bin`, not the `main` key or anything, so `require('sort-package-json')` should work absolutely fine. Definitely some tool is traversing `node_modules` in a non-standard way.

**Comment by keithamus** [comment]
Ahh - also it looks like you're using an outdated version of `sort-package-json` which _used_ to have `index.js` stand as both CLI and Library. If you update it might fix the problem.

**Comment by MrChocolatine** [comment]
I tried to clear and rebuild all my dependencies and everything seems to be back to normal now...
1. `rm yarn.lock`
2. `rm -rf node_modules tmp dist`
3. `yarn cache clean`
4. `yarn install`

What I still don't understand is that I simply rebuilt everything, I still have `sort-package-json@^1.22.1` in my `yarn.lock`, but now it works... Quite strange 🤔 .

**Comment by MrChocolatine** [comment]
Thank you very much for your time @keithamus.
