### ISSUE TITLE
sort-package-json packages/*/package.json does not work on Windows

### ISSUE THREAD

**Issue by tylerbutler** [keithamus/sort-package-json#73]
I don't understand why, but `sort-package-json packages/*/package.json` does not work on Windows. I get errors like this:

```
Error: ENOENT: no such file or directory, open 'packages/*/package.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at filesToProcess.forEach.filePath (C:\Users\tylerbu\code\sort-package-json\index.js:212:28)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\tylerbu\code\sort-package-json\index.js:211:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

I did some debugging, and it _looks_ like fs.readFileSync is behaving differently on Windows than on Linux. I can run the same command in WSL and it works fine. Not sure what's happening.

**Comment by tylerbutler** [comment]
Meant to add - I've tried various slash and backslash combinations to no effect.
